
//Get All notes
GET http://localhost:3000/notes HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE2Nzk4MDM4NDEsImFkbWluIjpmYWxzZX0.3aZ0gzv-86TTx0K9-MrU2Uo9xD7dF7tTAI-GbTIA7pA

###
//Get notes by id
GET http://localhost:3000/notes/20 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDEsImVtYWlsIjoiYWRpdWxhbGFtKzAwMDNAZ21haWwuY29tIiwiaXNfYWRtaW4iOnRydWUsImlhdCI6MTY4MDMxMDE5MiwiZXhwIjoxNjgwMzk2NTkyfQ.zqN1WycH1KN0oqz8Lb-hVPpRK9aumJfcL21FAyF5kHE

###
//Insert notes
post http://localhost:3000/notes HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDEsImVtYWlsIjoiYWRpdWxhbGFtKzAwMDNAZ21haWwuY29tIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2ODAzMTAxOTIsImV4cCI6MTY4MDM5NjU5Mn0.iMq8dmyv9N0g4oVCwfBM2vPoq7eEvJX4ENiFSabzkEU

{
  "note_title": "test",
  "note_description": "testr",
  "is_archived": true,
  "fk_user_id": 6
}

###
//Update note
PUT http://localhost:3000/notes/21 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDEsImVtYWlsIjoiYWRpdWxhbGFtKzAwMDNAZ21haWwuY29tIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2ODAzMTAxOTIsImV4cCI6MTY4MDM5NjU5Mn0.iMq8dmyv9N0g4oVCwfBM2vPoq7eEvJX4ENiFSabzkEU

{
  "note_title": "John",
  "note_description": "Doe",
  "is_archived": false
}

###
//delete note
DELETE http://localhost:3000/notes/22 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDEsImVtYWlsIjoiYWRpdWxhbGFtKzAwMDNAZ21haWwuY29tIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2ODAzMTAxOTIsImV4cCI6MTY4MDM5NjU5Mn0.iMq8dmyv9N0g4oVCwfBM2vPoq7eEvJX4ENiFSabzkEU

###
//Get All archived notes
GET http://localhost:3000/notes/isArchived HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDEsImVtYWlsIjoiYWRpdWxhbGFtKzAwMDNAZ21haWwuY29tIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2ODAzMTAxOTIsImV4cCI6MTY4MDM5NjU5Mn0.iMq8dmyv9N0g4oVCwfBM2vPoq7eEvJX4ENiFSabzkEU

###
//Get All NOT archived notes
GET http://localhost:3000/notes/isNotArchived HTTP/1.1

###
//Update note to archived by id
PUT http://localhost:3000/notes/setArchived/21 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDEsImVtYWlsIjoiYWRpdWxhbGFtKzAwMDNAZ21haWwuY29tIiwiaXNfYWRtaW4iOnRydWUsImlhdCI6MTY4MDMxMDE5MiwiZXhwIjoxNjgwMzk2NTkyfQ.zqN1WycH1KN0oqz8Lb-hVPpRK9aumJfcL21FAyF5kHE

###
//Update note to NOT archived by id
PUT http://localhost:3000/notes/setNotArchived/1 HTTP/1.1

###
//Get user by note id
GET http://localhost:3000/notes/2/user HTTP/1.1